version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp-volume:/var/www
    restart: always

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT_PASS: ${DB_ROOT_PASS}
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_ROOT_PASS: ${DB_ROOT_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        WP_ADM: ${WP_ADM}
        WP_ADM_PASS: ${WP_ADM_PASS}
        WP_ADM_MAIL: ${WP_ADM_MAIL}
        WP_USR: ${WP_USR}
        WP_USR_PASS: ${WP_USR_PASS}
        WP_USR_MAIL: ${WP_USR_MAIL}
        WP_URL: ${WP_URL}
        WP_TITLE: ${WP_TITLE}
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      WP_ADM: ${WP_ADM}
      WP_ADM_PASS: ${WP_ADM_PASS}
      WP_ADM_MAIL: ${WP_ADM_MAIL}
      WP_USR: ${WP_USR}
      WP_USR_PASS: ${WP_USR_PASS}
      WP_USR_MAIL: ${WP_USR_MAIL}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/
    restart: always

volumes:
  wp-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress/
    name: wp-volume
  db-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb/
    name: db-volume

networks:
  inception:
    driver: bridge
