version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp-volume:/var/www
    restart: always

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    secrets:
      - db_name
      - db_user
      - db_pass
      - db_root_pass
    environment:
      DB_NAME: /run/secrets/db_name
      DB_USER: /run/secrets/db_user
      DB_PASS: /run/secrets/db_pass
      DB_ROOT_PASS: /run/secrets/db_root_pass
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    secrets:
      - db_name
      - db_user
      - db_pass
      - wp_adm
      - wp_adm_pass
      - wp_adm_mail
      - wp_usr
      - wp_usr_pass
      - wp_usr_mail
      - wp_url
      - wp_title
    environment:
      DB_NAME: /run/secrets/db_name
      DB_USER: /run/secrets/db_user
      DB_PASS: /run/secrets/db_pass
      WP_ADM: /run/secrets/wp_adm
      WP_ADM_PASS: /run/secrets/wp_adm_pass
      WP_ADM_MAIL: /run/secrets/wp_adm_mail
      WP_USR: /run/secrets/wp_usr
      WP_USR_PASS: /run/secrets/wp_usr_pass
      WP_USR_MAIL: /run/secrets/wp_usr_mail
      WP_URL: /run/secrets/wp_url
      WP_TITLE: /run/secrets/wp_title
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/
    restart: always

secrets:
  db_name:
    file: ./secrets/db_name.txt
  db_user:
    file: ./secrets/db_user.txt
  db_pass:
    file: ./secrets/db_pass.txt
  db_root_pass:
    file: ./secrets/db_root_pass.txt
  wp_adm:
    file: ./secrets/wp_adm.txt
  wp_adm_pass:
    file: ./secrets/wp_adm_pass.txt
  wp_adm_mail:
    file: ./secrets/wp_adm_pass.txt
  wp_usr:
    file: ./secrets/wp_usr.txt
  wp_usr_pass:
    file: ./secrets/wp_usr_pass.txt
  wp_usr_mail:
    file: ./secrets/wp_usr_mail.txt
  wp_url:
    file: ./secrets/wp_url.txt
  wp_title:
    file: ./secrets/wp_title.txt

volumes:
  wp-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress/
    name: wp-volume
  db-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb/
    name: db-volume

networks:
  inception:
    driver: bridge
